### ISSUE TITLE
LB4Openshift-0.1 - Load balancer template

### ISSUE THREAD

**Issue by qwarz** [vmware-ibm-jil/vcd_toolkit_for_openshift#14]
Hello. 
Can you please tell me where to get the Lb4Openshift template if I am deploying not to IBM Cloud VMware Solutions Shared, but deploying Openshift to another VCD?

**Comment by tseelbach** [comment]
hi @qwarz - only way i know would be to download from IBM Cloud VMWare Solutions Shared public catalog

**Comment by tseelbach** [comment]
We are doing forward development to support OpenShift 4.6 +  in https://github.com/ibm-cloud-architecture/terraform-openshift4-vcd .   In that project we only use the coreOS base image, and build up the loadbalancer on top of that using Terraform.

Closing this here, since no action is planned in this repo
