### ISSUE TITLE
vmware-airgap: documentation: Create and configure Bastion VM

### ISSUE THREAD

**Issue by ianbaldwin2** [vmware-ibm-jil/vcd_toolkit_for_openshift#9]
Creating the bastion from template `vm-redhat7`
- I couldn't find the `root` password to login anywhere

Resolved by booting vm into single user mode and manually setting password.

I also noticed since this is publicly available, attempts to login to the vm from outside sources.

Resolution was to disable password login
- edit `/etc/ssh/sshd_config` and set password authentication to `no`
- add my id_rsa.pub ssh key to .ssh/authorised_keys on the bastion

**Comment by tseelbach** [comment]
fixed the password setup instructions here https://github.com/ibm-cloud-architecture/terraform-openshift4-vcd/blob/master/README.md#create-and-configure-bastion-vm

I added the ssh key login  suggestion into the readme as well

We won't fix this in this repo since we are doing 4.6+ OpenShift support in the terraform-openshift4-vcd repo
